const Performances = [

  
  {
    tickets: "true",
    ticketLink: "https://www.auburnsymphony.com/concerts/mothers-day-season-finale-2023-ode-to-joy/",
    role: "Soloist",
    opera: "Beethoven 9th",
    composer: "Beethoven",
    company: "Auburn Symphony",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1659297756/robertbalonek.com/Logos/Screen_Shot_2022-07-31_at_1.01.59_PM_tz3qia.png",
    dates: "May 14th 2023",
    venue: "Mondavi Center for the Performing Arts, UC Davis",
    modalImages: [
      
    ],
  },
  {
    tickets: "true",
    ticketLink: "https://secure.operasj.org/overview/tosca",
    role: "Angelotti (Scarpia Cover)",
    opera: "Tosca",
    composer: "Puccini",
    company: "Opera San jose",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1659296557/robertbalonek.com/Logos/Screen_Shot_2022-07-31_at_12.41.41_PM_v5dhbl.png",
    dates: "April 15-30 2023",
    venue: "California Theater, San Jose CA",
    modalImages: [
      
    ],
  },
  {
    tickets: "true",
    ticketLink: "https://secure.operasj.org/overview/falstaff",
    role: "Ford (Cover)",
    opera: "Falstaff",
    composer: "Verdi",
    company: "Opera San jose",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1659296557/robertbalonek.com/Logos/Screen_Shot_2022-07-31_at_12.41.41_PM_v5dhbl.png",
    dates: "Feb 11-26 2023",
    venue: "California Theater, San Jose CA",
    modalImages: [
      
    ],
  },
  {
    tickets: "false",
    ticketLink: "https://www.operasj.org/the-marriage-of-figaro-ticketpage/",
    role: "Count (Cover)",
    opera: "Le Nozze di Figaro",
    composer: "Mozart",
    company: "Opera San Jose",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1659296557/robertbalonek.com/Logos/Screen_Shot_2022-07-31_at_12.41.41_PM_v5dhbl.png",
    dates: "September 10-25th 2022",
    venue: "California Theater, San Jose CA",
    modalImages: [
      
    ],
  },
  {
    tickets: "false",
    ticketLink: "https://tickets.galloarts.org/8566", //"https://www.operamodesto.org/concerts/",
    role: "Marcello",
    opera: "La Boheme",
    composer: "Puccini",
    company: "Opera Modesto",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624394360/robertbalonek.com/Logos/OperaModesto_tggc0y.jpg",
    dates: "April 30- May 1 2022",
    venue: "Gallo Center for the Arts, CA",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195525/robertbalonek.com/Performances/Boheme%20-%20Marcello%20-%202022/IMG_4338_jktckl.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195537/robertbalonek.com/Performances/Boheme%20-%20Marcello%20-%202022/Marcello_Painting_2_ypefmx.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195538/robertbalonek.com/Performances/Boheme%20-%20Marcello%20-%202022/190A7334_wdrhpx.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195530/robertbalonek.com/Performances/Boheme%20-%20Marcello%20-%202022/Butt_Warm_esa6bj.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195529/robertbalonek.com/Performances/Boheme%20-%20Marcello%20-%202022/190A7350_uih3xg.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195529/robertbalonek.com/Performances/Boheme%20-%20Marcello%20-%202022/Musetta_mimi_wif2lh.jpg",
    ],
  },
  {
    // tickets: "true",
    ticketLink: "https://www.bohemeopera.com/main-stage",
    role: "Rigoletto",
    opera: "Rigoletto",
    composer: "Verdi",
    company: "Boheme opera of NJ",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145907/robertbalonek.com/Logos/p3789966395-11_g5a6um.jpg",
    dates: "April 1-3, 2022",
    venue: "Kendall Hall, Performance Theater NJ",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194975/robertbalonek.com/Performances/Rigoletto%202022/bo_220315-012_ocqmwn.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194975/robertbalonek.com/Performances/Rigoletto%202022/bo_220315-031_jzagwa.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194977/robertbalonek.com/Performances/Rigoletto%202022/bo_220315-025_r1bzyq.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194980/robertbalonek.com/Performances/Rigoletto%202022/IMG_4226_fz6tix.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200505/robertbalonek.com/Performances/Rigoletto%202022/prpv_sy58q3.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200504/robertbalonek.com/Performances/Rigoletto%202022/prpv_54_tkg2mz.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200499/robertbalonek.com/Performances/Rigoletto%202022/prpv_46_frgzkk.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200494/robertbalonek.com/Performances/Rigoletto%202022/prpv_39_ylt7h0.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200493/robertbalonek.com/Performances/Rigoletto%202022/prpv_32_n6greb.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200489/robertbalonek.com/Performances/Rigoletto%202022/prpv_36_xi3rqs.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200476/robertbalonek.com/Performances/Rigoletto%202022/prpv_9_wnoxig.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200485/robertbalonek.com/Performances/Rigoletto%202022/prpv_34_aswopy.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200486/robertbalonek.com/Performances/Rigoletto%202022/prpv_27_pvmnhl.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200482/robertbalonek.com/Performances/Rigoletto%202022/prpv_20_vf7yto.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200505/robertbalonek.com/Performances/Rigoletto%202022/prpv_56_akklum.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651200469/robertbalonek.com/Performances/Rigoletto%202022/prpv_5_e70bxa.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651195038/robertbalonek.com/Performances/Rigoletto%202022/Rig_Cutout_ohbkba.png",
    ],
    reviews: [
      {
        Quote:
          "Balonek was able to scurry through crowd scenes with elastic physicality as well as express parental tenderness toward his daughter Gilda. He was alternately sprightly,animated, and conniving, with a solid voice carrying well into the house. Balonek showed particularly sensitive dynamics in an Act I soliloquy, while both scheming with the professional assassin Sparafucile and offering protective advice to Gilda.",
        From: "Nancy Plum, Town Topics",
      },
      
    ],
  },
  {
    // tickets: "true",
    ticketLink: "https://nycopera.com/shows/finzi/",
    role: "Ernesto",
    opera: "The garden of the Finzi-Continis",
    composer: "Ricky Ian Gordon",
    company: "NYC Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601215498/robertbalonek.com/Logos/NYCOpera_szn6kj.png",
    dates: "Jan 19-30 2022",
    venue: "National Yiddish Theatre, NYC",
    modalImages: [
      // "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601215498/robertbalonek.com/Logos/NYCOpera_szn6kj.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194562/robertbalonek.com/Performances/Garden%20of%20the%20Finzi%20Contini/Finzi_c0wcq6.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194500/robertbalonek.com/Performances/Garden%20of%20the%20Finzi%20Contini/Bob_DSCF8802_n5ewdm.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194499/robertbalonek.com/Performances/Garden%20of%20the%20Finzi%20Contini/Bob_DSCF8976_myldwo.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194488/robertbalonek.com/Performances/Garden%20of%20the%20Finzi%20Contini/Bob_DSCF8787_voregp.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194454/robertbalonek.com/Performances/Garden%20of%20the%20Finzi%20Contini/merchant_jfsiad.jpg"
    ],
  },
  
  {
    // tickets: "true",
    ticketLink: "https://www.operaonthejames.org/shows",
    role: "Figaro",
    opera: "Barber of Seville",
    composer: "Rossini",
    company: "Opera On the James",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624389679/robertbalonek.com/Performances/OOTJ%20Figaro/OOTJ_l2gjb0.webp",
    dates: "Nov 12-14 2021",
    venue: "Academy Center for the Arts, VA",
    modalImages: [
      // "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624389679/robertbalonek.com/Performances/OOTJ%20Figaro/OOTJ_l2gjb0.webp",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194808/robertbalonek.com/Performances/Barber%20of%20Seville%202021/Figaro_copy_qz5dob.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194775/robertbalonek.com/Performances/Barber%20of%20Seville%202021/Fig_Count_Chin_zjxru0.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194780/robertbalonek.com/Performances/Barber%20of%20Seville%202021/Figaro_Rosina_hetaha.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1651194770/robertbalonek.com/Performances/Barber%20of%20Seville%202021/Closer1_zw1o6p.png"
    ],
  },
  {
    role: "Shaunard",
    opera: "La Boheme",
    composer: "Puccini",
    company: "New york City Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601215498/robertbalonek.com/Logos/NYCOpera_szn6kj.png",
    dates: "May 20 2019",
    venue: "Bryant Park NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386343/robertbalonek.com/Performances/NYCO%20Boheme%202019/NYCO_Shaunard_ug67s5.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386492/robertbalonek.com/Performances/NYCO%20Boheme%202019/BohemeNYCO_fvypmj.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601215498/robertbalonek.com/Logos/NYCOpera_szn6kj.png",
    ],
  },
  {
    role: "Owen",
    opera: "Owen Wingrave",
    composer: "Britten",
    company: "Little Opera Theater of NY",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145668/robertbalonek.com/Logos/Lil_Opera_irzsbz.jpg",
    dates: "May 9 - May 12 2019",
    venue: "GK Arts Center Brooklyn NY",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624384073/robertbalonek.com/Performances/Owen%20Wingrave%20LOTNY/Owen2_xnwmh5.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624384075/robertbalonek.com/Performances/Owen%20Wingrave%20LOTNY/Owen3_g1mv25.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145669/robertbalonek.com/Logos/OwenWingrave_hncpvc.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624384164/robertbalonek.com/Performances/Owen%20Wingrave%20LOTNY/Screen_Shot_2021-06-22_at_10.48.30_AM_fnjrpm.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624384075/robertbalonek.com/Performances/Owen%20Wingrave%20LOTNY/Owen1_nwcyoq.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145668/robertbalonek.com/Logos/Lil_Opera_irzsbz.jpg",
    ],
    reviews: [
      {
        Quote:
          "Robert Balonek was a heart-rending Owen Wingrave with a powerful and commanding baritone capable of tenderness and vulnerability.",
        From: "Steven Jude Tietjen, Opera News",
      },
      {
        Quote:
          "Balonek, a sturdy and distinguished baritone to whom the tessitura and Britten’s curious lines made no difficulty at all.",
        From: "Parterre.com",
      },
    ],
  },
  {
    role: "Bass Soloist",
    opera: "Christmas Oratorio",
    composer: "Bach",
    company: "Canterbury Choral Society",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145907/robertbalonek.com/Logos/Canterbury_yzrqt6.png",
    dates: "November 24 2019",
    venue: "Church of the Heavenly Rest 2 E 90th St NYC",
    modalImages: [
      // "https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/76678693_2566296236741047_4838667549598023680_n.jpg?_nc_cat=100&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=DSS4EyQjwL0AX90pkN1&_nc_ht=scontent-sjc3-1.xx&oh=429e14c0270429c51b403c4500c7045c&oe=60D66422",
      // "https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/75250852_2566296153407722_197012121257508864_n.jpg?_nc_cat=106&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=3R8PXUsTKLMAX83Q1bk&tn=FGEb_RwRLvx5qKiF&_nc_ht=scontent-sjc3-1.xx&oh=e7575e884d8687d64b2084a4293126f0&oe=60D7023D",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386609/robertbalonek.com/Performances/Canterbury/Canterbury1_r61z1t.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145907/robertbalonek.com/Logos/Canterbury_yzrqt6.png",
    ],
  },
  {
    role: "Shaunard",
    opera: "La Boheme",
    composer: "Puccini",
    company: "Piedmont Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221292/PiedmontOpera.png",
    dates: "October 30 - Nov 1",
    venue: "Steven Center, Winston-Salem NC",
    modalImages: [
      // "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221292/PiedmontOpera.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221847/robertbalonek.com/BobLiveShots/2_paeohz.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221847/robertbalonek.com/BobLiveShots/IMG_2642_2.JPG_aiepat.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221847/robertbalonek.com/BobLiveShots/IMG_2598.JPG_a7qc3b.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221847/robertbalonek.com/BobLiveShots/IMG_2592.JPG_pqvtap.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601221839/robertbalonek.com/BobLiveShots/IMG_2599_spwf9i.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386529/robertbalonek.com/Performances/Piedmont%20Boheme%202019/PiedmontShaunard2_d3pwha.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386534/robertbalonek.com/Performances/Piedmont%20Boheme%202019/PiedmontShaunard_lssvki.jpg",
    ],
    reviews: [
      {
        Quote:
          "Steven LaCosse, the stage director, uses the physicality of his singers to great effect, especially Balonek, who might well be the most acrobatic opera singer I have ever seen. His antics are dazzling, and his voice is, too.",
        From: "Winston-Salem Journal",
      },
      {
        Quote:
          "Schaunard, the musician, was beautifully sung by Robert Balonek, whose acting was convincing and comedy hilarious.",
        From: "Classical Voice North Carolina",
      },
    ],
  },
  {
    role: "Schicchi",
    opera: "Gianni Schicchi",
    composer: "Puccini",
    company: "PAC at Purchase",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387073/robertbalonek.com/Performances/Gianni%20Schicchi%20Purchase/PAC_Logo_dtnqtu.png",
    dates: "September 28 2019",
    venue: "Gerald Lynch Theater NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386914/robertbalonek.com/Performances/Gianni%20Schicchi%20Purchase/Schicchi1_tq8e6z.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386913/robertbalonek.com/Performances/Gianni%20Schicchi%20Purchase/Schicchi2_msjmkp.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387073/robertbalonek.com/Performances/Gianni%20Schicchi%20Purchase/PAC_Logo_dtnqtu.png",
    ],
  },
  {
    role: "Figaro",
    opera: "Barber of Seville",
    composer: "Rossini",
    company: "Boston Midsummer Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387480/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/BMO_Logo_ailrn2.jpg",
    dates: "July 25-29 2018",
    venue: "Mosesian Center for the Arts, Watertown, MA",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387370/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/a2b5bb_9d050b2d5ef346b0b97f2d5ed405f943_mv2_d_3835_1573_s_2_llai29.webp",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387366/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/a2b5bb_3e6330c310d54688b81892e9bc4b0b16_mv2_d_2848_4288_s_4_2_myyvb1.webp",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387363/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/a2b5bb_3a2951cf560349f78f6dbcda525da288_mv2_d_2848_4288_s_4_2_dyfglz.webp",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386716/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/Barber3_ufcc2h.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386716/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/Barber2_tc8fsu.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386716/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/Barber1_utuzqr.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624387334/robertbalonek.com/Performances/Boston%20Midsummer%20Barber/BarberPoster_vwrvld.webp",
    ],
    reviews: [
      {
        Quote:
          "When Figaro (Robert Balonek) burst into the arena with effortless energy and bravado, he shook hands with audience members in the first row and roamed through the aisles greeting people...the star was Robert Balonek. He should be singing Figaro or Lepporello at the Met.",
        From: "Classical-Scene.com",
      },
      {
        Quote:
          "As the eponymous barber, Robert Balonek relied heavily on boyish charm, bouncing about in an exuberant manner.   His baritone energetically delivered the famous aria, “Largo al factotum.”",
        From: "http://stephencera.com/boston-barber-less-can/",
      },
    ],
  },
  {
    role: "Captain / Max",
    opera: "Candide",
    composer: "Bernstein",
    company: "South Dakota Symphony",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388307/robertbalonek.com/Performances/Candide/SDSOLogo_feyldv.jpg",
    dates: "April 21-22 2018",
    venue: "Washington Pavilion, SD",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388212/robertbalonek.com/Performances/Candide/Pavillion_vvetyh.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388133/robertbalonek.com/Performances/Candide/Max1_um6cxv.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388131/robertbalonek.com/Performances/Candide/CandideCast_nfxaty.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388130/robertbalonek.com/Performances/Candide/Captain_t65nhe.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388307/robertbalonek.com/Performances/Candide/SDSOLogo_feyldv.jpg",
    ],
  },
  {
    role: "Shaunard",
    opera: "La Boheme",
    composer: "Puccini",
    company: "South Dakota Symphony",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388307/robertbalonek.com/Performances/Candide/SDSOLogo_feyldv.jpg",
    dates: "March 18-20 2016",
    venue: "Washington Pavilion, SD",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624388307/robertbalonek.com/Performances/Candide/SDSOLogo_feyldv.jpg",
      // "https://youtu.be/Z1QB8nAEOBM",
    ],
  },
  {
    role: "Figaro",
    opera: "Le Nozze di Figaro",
    composer: "Mozart",
    company: "Opera on the James",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624389679/robertbalonek.com/Performances/OOTJ%20Figaro/OOTJ_l2gjb0.webp",
    dates: "March 20th-22nd, 2015",
    venue: "Academy of Fine Arts, VA",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624389679/robertbalonek.com/Performances/OOTJ%20Figaro/OOTJ_l2gjb0.webp",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624389679/robertbalonek.com/Performances/OOTJ%20Figaro/OOTJPoster_cqcb22.webp",
    ],
  },
  {
    role: "Count",
    opera: "Le Nozze di Figaro",
    composer: "Mozart",
    company: "Salt Marsh Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/Salt_Marsh_wdwg0q.png",
    dates: "Oct 1-5, 2014",
    venue: "The Kate in Old Saybrook, CT",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624389950/robertbalonek.com/Performances/Salt%20Marsh%20Figaro/The_Kate_in_Old_Saybrook_CT_bwt7nu.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390106/robertbalonek.com/Performances/Salt%20Marsh%20Figaro/Count2_yllftj.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390106/robertbalonek.com/Performances/Salt%20Marsh%20Figaro/Count4_w7dagt.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390106/robertbalonek.com/Performances/Salt%20Marsh%20Figaro/Count1_igqft3.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390106/robertbalonek.com/Performances/Salt%20Marsh%20Figaro/Count3_yhfgyt.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/Salt_Marsh_wdwg0q.png",
    ],
  },
  {
    role: "Guglielmo",
    opera: "Cosi Fan Tutte",
    composer: "Mozart",
    company: "NY Opera CoOp",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390616/robertbalonek.com/Performances/Opera%20CoOp%20cosi/CoOp_Logo_vb9gs9.png",
    dates: "Feb 18-27, 2015",
    venue: "106 East 86th Street NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390616/robertbalonek.com/Performances/Opera%20CoOp%20cosi/OperaCoop_y5arkr.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390616/robertbalonek.com/Performances/Opera%20CoOp%20cosi/Coop2_twxh2q.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624390616/robertbalonek.com/Performances/Opera%20CoOp%20cosi/CoOp_Logo_vb9gs9.png",
    ],
  },
  {
    role: "Silvio",
    opera: "Pagliacci",
    composer: "Leoncavallo",
    company: "NY Vocal Productions",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145671/robertbalonek.com/Logos/Vocal_Productions_Logo_ids1en.png",
    dates: "Feb 18-27, 2015",
    venue: "106 East 86th Street NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145671/robertbalonek.com/Logos/Vocal_Productions_Logo_ids1en.png",
    ],
  },
  {
    role: "Jose Castro",
    opera: "Natoma",
    composer: "Herbert",
    company: "Victor Herbert Renaissance Project",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/VHRP_fajuvy.png",
    dates: "July 15, 2014",
    venue: "NYC",
    modalImages: [
      "https://vhrplive.org/wp-content/uploads/2014/02/victor-herberts-natoma-the-politics-of-american-grand-opera.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/VHRP_fajuvy.png",
    ],
  },
  {
    role: "Paul Revere",
    opera: "Boston Tea Party",
    composer: "M. Zachary Johnson",
    company: "Encomapass Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145667/robertbalonek.com/Logos/7098058_orig_lwmtyr.jpg",
    dates: "Aug 8-24, 2014",
    venue: "NYC Fringe Festival",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145667/robertbalonek.com/Logos/7098058_orig_lwmtyr.jpg",
      // "https://scontent-sjc3-1.xx.fbcdn.net/v/t1.18169-9/945359_197744590372874_763476624_n.jpg?_nc_cat=102&ccb=1-3&_nc_sid=9267fe&_nc_ohc=gHPvdbuY1ucAX_vVOVR&_nc_ht=scontent-sjc3-1.xx&oh=1cb0185a3ca3074e0728c9165b341cc6&oe=60D7C958",
    ],
  },
  {
    role: "Ford",
    opera: "Falstaff",
    composer: "Verdi",
    company: "Utopia Opera",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624391490/robertbalonek.com/Logos/Screen_Shot_2021-06-22_at_12.50.04_PM_zfnkea.png",
    dates: "June 28, 2014",
    venue: " Lang Recital Hall NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145742/robertbalonek.com/BobLiveShots/IMG_7980_copy.JPG_bxtgpy.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145741/robertbalonek.com/BobLiveShots/IMG_7955.JPG_c8m0ib.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624391490/robertbalonek.com/Logos/Screen_Shot_2021-06-22_at_12.50.04_PM_zfnkea.png",
    ],
  },
  {
    role: "Escamillo",
    opera: "Carmen",
    composer: "Bizet",
    company: "Opera Hamilton",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145668/robertbalonek.com/Logos/Opera_Hamilton_2_ry8b7h.jpg",
    dates: "production cancelled",
    venue: "Dofasco Centre for the Arts ON",
    modalImages: [
      "http://operahamilton.ca/imgs/exterior.jpg",
      "http://operahamilton.ca/imgs/dofasco.gif",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145668/robertbalonek.com/Logos/Opera_Hamilton_lv2w3x.jpg",
    ],
  },
  {
    role: "Charon",
    opera: "Alceste",
    composer: "Handel",
    company: "American Classical Orchestra",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145667/robertbalonek.com/Logos/ACO_ddy0do.jpg",
    dates: "March 21, 2014",
    venue: "Alice Tully Hall NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145742/robertbalonek.com/BobLiveShots/Charon_hy59yl.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624391888/robertbalonek.com/Performances/Alceste%20ACO/Alceste_aewsbg.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624391888/robertbalonek.com/Performances/Alceste%20ACO/Alceste2_yr88es.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145667/robertbalonek.com/Logos/ACO_ddy0do.jpg",
    ],
    reviews: [
      {
        Quote:
          "The (unintentional) scene-stealer was Robert Balonek, whose entry as Charon... cut an imposing figure, singing his aria with a crisp baritone that had just the right hint of darkness for the ferryman of the dead.",
        From: "Superconductor",
      },
      {
        Quote:
          "Baritone Robert Balonek’s one aria, “Ye fleeting shades, I come,” was persuasive, polished and robust.",
        From: "seenandheard-international.com",
      },
    ],
  },
  {
    role: "Jaap",
    opera: "Steal a Pencil for Me",
    composer: "Gerald Cohen",
    company: "Gerald Cohen",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145669/robertbalonek.com/Logos/Pencil_ar1ajl.jpg",
    dates: "Jan 16, 2014",
    venue: "National Opera Center NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/Steal_A_Pencil_for_Me_lr8pnx.png",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624386731/robertbalonek.com/Performances/Steal%20a%20pencil/StealAPencilGroup_dlakqu.jpg",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145669/robertbalonek.com/Logos/Pencil_ar1ajl.jpg",
      "https://i.ytimg.com/vi/N7Gr0ArKB6I/mqdefault.jpg",
    ],
  },
  {
    role: "Paul Conti",
    opera: "Figaro 90210",
    composer: "Mozart / Guerrerio",
    company: "NSD Theater",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/Figaro90210_hzti7p.gif",
    dates: "June 11-16, 2013",
    venue: "151 Bank Street NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145670/robertbalonek.com/Logos/Figaro90210_hzti7p.gif",
      "https://www.thewriteteachers.com/wp-content/uploads/2013/06/KAF_5323-L.jpg",
      "https://www.thewriteteachers.com/wp-content/uploads/2013/06/KA2_4917-L.jpg",
      "https://www.thewriteteachers.com/wp-content/uploads/2013/06/KAF_5199-L.jpg",
      "http://parterre.com/wp-content/uploads/2013/06/figaro_2.jpg",
    ],
  },
  {
    role: "Blondel",
    opera: "Richard Coeur de Lion",
    composer: "Handel",
    company: "American Classical Orchestra",
    logo: "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145667/robertbalonek.com/Logos/ACO_ddy0do.jpg",
    dates: "March 21, 2011",
    venue: "Alice Tully Hall NYC",
    modalImages: [
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1601145667/robertbalonek.com/Logos/ACO_ddy0do.jpg",
      "https://static01.nyt.com/images/2011/05/20/arts/Lionheart/Lionheart-jumbo.jpg?quality=90&auto=webp",
      "https://res.cloudinary.com/bobalobbadingdong/image/upload/v1624393202/robertbalonek.com/BobLiveShots/Screen_Shot_2021-06-22_at_1.19.37_PM_jdqeqj.png",
    ],
    reviews: [
      {
        Quote:
          "...The lead role, really, is Blondel, here the hearty baritone Robert Balonek, who was endearing in the scenes in which the squire seeks guidance from Antonio",
        From: "NY Times",
      },
      {
        Quote:
          "Balonek, in the starring role of the troubadour Blondel, revealed a light, full, meaty, attractive baritone that made this faithful intriguer comprehensible and sympathetic, and he’s easy on the eyes as well as the ears. I look forward to hearing him again.",
        From: "operatoday.com",
      },
    ],
  },
];

export default Performances;
